config/routes.rb
Rails.application.routes.draw do
  root 'landings#new'
  get 'thankyou' => 'landings#thankyou'
  get 'index' => 'landings#index'  
  resources :landings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/landing.rb
class Landing < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  before_action :set_landing, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "example", password: "pa$$w0rd", except: [:new, :create, :thankyou]
  # GET /landings
  # GET /landings.json
  def index
    @landings = Landing.all
  end

  def thankyou
  end

  # GET /landings/1
  # GET /landings/1.json
  def show
  end

  # GET /landings/new
  def new
    @landing = Landing.new
  end

  # GET /landings/1/edit
  def edit
  end

  # POST /landings
  # POST /landings.json
  def create
    @landing = Landing.new(landing_params)

    respond_to do |format|
      if @landing.save
        WelcomeMailer.welcome(@landing).deliver
        format.html { redirect_to thankyou_path, notice: 'Success!' }
        format.json { render :show, status: :created, location: @landing }
      else
        format.html { render :new }
        format.json { render json: @landing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /landings/1
  # PATCH/PUT /landings/1.json
  def update
    respond_to do |format|
      if @landing.update(landing_params)
        format.html { redirect_to @landing, notice: 'Landing was successfully updated.' }
        format.json { render :show, status: :ok, location: @landing }
      else
        format.html { render :edit }
        format.json { render json: @landing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /landings/1
  # DELETE /landings/1.json
  def destroy
    @landing.destroy
    respond_to do |format|
      format.html { redirect_to landings_url, notice: 'Landing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_landing
      @landing = Landing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def landing_params
      params.require(:landing).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/views/landings/_form.html.erb
<%= form_with(model: landing, local: true) do |form| %>
  <% if landing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(landing.errors.count, "error") %> prohibited this landing from being saved:</h2>

      <ul>
      <% landing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group">
    <%= form.text_field :email, label: false, placeholder: "Email"%>
  </div>
  <div>
    <%= form.submit "Notify Me", class: "btn-custom" %>
  </div>  
<% end %>

app/views/landings/edit.html.erb
<h1>Editing Landing</h1>

<%= render 'form', landing: @landing %>

<%= link_to 'Show', @landing %> |
<%= link_to 'Back', landings_path %>

app/views/landings/index.html.erb
<div class="index overlay">
  <h2>Captured Emails</h2>
  <% @landings.each do |landing| %>
    <tr>
      <p><%= landing.email %> | <%= link_to 'Delete', landing, method: :delete, data: { confirm: 'Are you sure?' } %></p>
    </tr>
  <% end %>
<br>
  <%= link_to 'Home', root_path %>
</div>

app/views/landings/new.html.erb
<div class="center">
<img src="assets/logo.png" id="logo">
	<h4 class="header">We're building something awesome, sign-up to find out when it's available.</h4>
	<div class="main">
		<%= render 'form', landing: @landing %>
		<div class="social center">
			<a href="#"><i class="fa fa-facebook"></i></a>
			<a href="#"><i class="fa fa-twitter"></i></a>
			<a href="#"><i class="fa fa-instagram"></i></a>
		</div>
	</div>
</div>		

app/views/landings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @landing.email %>
</p>

<%= link_to 'Edit', edit_landing_path(@landing) %> |
<%= link_to 'Back', landings_path %>

app/views/landings/thankyou.html.erb
<div class="center">
<img src="/assets/logo.png" id="logo">
	<h4 class="header">Thank you for your interest, we'll be sending you updates periodically on our progress.</h4>
	<div class="main">
		<%= link_to 'Back', root_path, class: "btn-custom" %>
		<br>
		<div class="social center">
			<!-- <a href="#"><i class="fa fa-facebook"></i></a> <--></-->
			<%= link_to "#" do %>
				<i class="fa fa-facebook"></i>
			<% end %>
			<a href="#"><i class="fa fa-twitter"></i></a>
			<a href="#"><i class="fa fa-instagram"></i></a>
		</div>
	</div>
</div>		

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LandingPage</title>
    <meta name="description" content="Demo - Fullscreen Landing Page" />
    <meta name="keywords" content="open, source, fullscreen, image, coming, soon, pre, launch, landing, page, construction, lead, generation, rails, collect, email, sign-up, collection, beta, code, free, demo, tutorial, github" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="background-image">
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer><a href="https://github.com/mhill426/rails-landing-page" target="_blank">Open Source</a> by <a href="http://matthewdhill.com" target="_blank">Matthew D. Hill</a><br>Bike designed by <a href="http://www.huge-design.com" target="_blank">Huge-Design</a></footer>